import test from 'node:test';
import { Hosts } from '../src/server/hosts.js';
import { HostFloors, hostParts, startHooks } from '../src/server/host-floor.js';
import { FLOORHOST_PROTOCOL } from '../src/shared/floorhost.js';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync, readFileSync, rmSync, mkdirSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { tmpdir } from 'node:os';
import { WebSocket } from 'ws';
import { loadConfig } from '../src/server/config.js';
import { startServer } from '../src/server/server.js';
import type { TeamState } from '../src/shared/master-workers.js';

test('remote mixed-provider team uses host-local worktrees, authenticated tools and one verified PR',{timeout:60000},async()=>{
 const dir=mkdtempSync(path.join(tmpdir(),'office-team-server-')),bin=path.join(dir,'bin');mkdirSync(bin);
 const fake=`#!${process.execPath}\nif(process.argv.includes('--version')){console.log('1.0.0');process.exit(0);}setInterval(()=>{},1000);\n`;
 for(const name of ['claude','codex'])writeFileSync(path.join(bin,name),fake,{mode:0o755});
 const pulls=path.join(dir,'pulls.json');writeFileSync(pulls,'[]');
 writeFileSync(path.join(bin,'gh'),`#!${process.execPath}\nimport {readFileSync} from 'node:fs';\nconst a=process.argv.slice(2);console.log(a[0]==='pr'&&a[1]==='list'&&a[a.indexOf('--state')+1]==='open'?readFileSync(${JSON.stringify(pulls)},'utf8'):'[]');\n`,{mode:0o755});
 const oldPath=process.env.PATH;process.env.PATH=`${bin}${path.delimiter}${oldPath}`;
 const git=(cwd:string,...args:string[])=>execFileSync('git',args,{cwd,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();
 git(dir,'init','-q','-b','main');writeFileSync(path.join(dir,'README.md'),'# fixture\n');git(dir,'add','README.md');git(dir,'-c','user.name=Test','-c','user.email=test@example.test','commit','-qm','initial');
 const home=path.join(dir,'office-home');mkdirSync(home);
 const cfg=loadConfig(['--home',home,'--password','team-test','--no-open']);cfg.port=0;
 const hosts=new Hosts(cfg.dataDir),code=hosts.pair('Tester');assert.notEqual(typeof code,'string');
 const paired=hosts.claim((code as any).code,'Remote team host');assert.notEqual(typeof paired,'string');
 writeFileSync(path.join(cfg.dataDir,'floors.json'),JSON.stringify([{id:'remote-team',name:'Remote team project',dir,palette:0,addedBy:'Tester',addedAt:Date.now(),host:(paired as any).host.id}]));
 const office=await startServer(cfg);let ws:WebSocket|undefined,state:TeamState|undefined;
 let host:HostFloors|undefined,hostWs:WebSocket|undefined;
 const hooks=await startHooks(id=>host?.workersOf(id),undefined,(req,res,url)=>host?.teams.hook(req,res,url,id=>host?.floorOf(id))??Promise.resolve(false));
 const wait=async(check:()=>boolean)=>{const end=Date.now()+10000;while(!check()&&Date.now()<end)await new Promise(r=>setTimeout(r,20));assert.ok(check(),'condition timed out');};
 try {
  const base=`http://127.0.0.1:${(office.server.address() as any).port}`;
  hostWs=new WebSocket(base.replace('http:','ws:')+'/floor-host');
  const send=(m:unknown)=>hostWs?.readyState===WebSocket.OPEN&&hostWs.send(JSON.stringify(m));
  host=new HostFloors(hostParts({dataDir:path.join(dir,'host-data'),agentCmd:path.join(bin,'claude'),agentArgs:[],dshProfile:'acp'},send,hooks.url,5));
  hostWs.on('open',()=>send({t:'hello',hostId:(paired as any).host.id,token:(paired as any).token,protocol:FLOORHOST_PROTOCOL}));
  hostWs.on('message',raw=>{const msg=JSON.parse(String(raw));if(msg.t==='welcome')void host!.open(msg.floors);else void host!.call(msg);});
  await wait(()=>!!host!.floors.get('remote-team')?.project);
  const floor=host.floors.get('remote-team')!;await floor.ready;assert.ok(floor.project.agentProviders.includes('codex'));

  const login=await fetch(base+'/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:'team-test'})});assert.equal(login.status,200);
  const cookie=login.headers.getSetCookie().map(c=>c.split(';')[0]).join('; ');
  ws=new WebSocket(base.replace('http:','ws:')+'/ws?name=TeamTester&lite=1',{headers:{Cookie:cookie,Origin:base}});
  ws.on('message',raw=>{const m=JSON.parse(String(raw));if(m.t==='welcome'||m.t==='floor.enter')state=m.masterWorkers;else if(m.t==='master-workers')state=m.state;});
  await wait(()=>!!state);
  ws.send(JSON.stringify({t:'master-workers.start',request:{master:{provider:'claude',model:'opus'},models:[{provider:'codex',model:'gpt-5.4-mini'},{provider:'claude',model:'haiku'}],maxWorkers:5,brief:'Implement a tested API and deliver a single PR',requirements:['Add API file','Verify implementation']}}));
  await wait(()=>!!state?.current?.masterId);
  const m=state!.current!.masterId!;
  const saved=()=>JSON.parse(readFileSync(path.join(dir,'.agent-office','workers.json'),'utf8'));
  const call=async(id:string,route:string,b?:unknown,wrong=false)=>{
   const token=saved().find((w:any)=>w.id===id)?.hookToken;
   const res=await fetch(`${hooks.url}${route}?worker=${id}`,{method:b?'POST':'GET',headers:{authorization:`Bearer ${wrong?'wrong':token}`,'content-type':'application/json'},...(b?{body:JSON.stringify(b)}:{})});return {status:res.status,body:await res.json() as any};
  };
  const act=async(id:string,b:object)=>{const current=(await call(id,'/office/team')).body.current;return call(id,'/office/team',{id:current.id,revision:current.revision,...b});};
  assert.equal((await call(m,'/office/team',undefined,true)).status,401);
  const observer=floor.workers.spawn('desk-3','test','Observe the office',false,'agent','claude','sonnet');assert.ok(typeof observer!=='string');
  assert.match(floor.workers.prompt(m,'Unrelated task','Boss')!,/managed/);
  assert.equal((await call(observer.id,'/office/team')).status,400,'ordinary workers cannot enter team control');
  assert.equal((await call(m,'/office/workers/inbox')).status,200,'remote participants have an authenticated inbox');
  for(const route of ['/office/workers','/office/workers/home','/office/workers/helper','/office/queue'])assert.equal((await call(m,route,{prompt:'unrelated',provider:'claude',model:'haiku'})).status,403);
  assert.equal((await act(m,{action:'plan',plan:'Delegate scoped API implementation, inspect and integrate, then verify the final branch',tasks:[{id:'api',title:'API implementation',instructions:'Add the API implementation file',acceptance:'API file exists and tests pass',files:['api.ts'],dependencies:[]},{id:'recovery',title:'Recover a partial failure',instructions:'Exercise failure recovery while preserving partial work',acceptance:'Partial worker work survives and the master takes over',files:['partial.ts'],dependencies:[]}]})).status,200);
  const master=floor.workers.get(m)!;const masterDir=path.join(dir,master.worktree!.path);
  writeFileSync(path.join(masterDir,'contract.ts'),'export const contract = true;\n');git(masterDir,'add','contract.ts');git(masterDir,'-c','user.name=Test','-c','user.email=test@example.test','commit','-qm','master contract');const masterHead=git(masterDir,'rev-parse','HEAD');
  assert.equal((await act(m,{action:'dispatch',task:'api',choice:{provider:'codex',model:'gpt-5.4-mini'},reason:'Scoped implementation suitable for this eligible worker'})).status,200);
  const r=(await call(m,'/office/team')).body.current,w=r.tasks[0].attempts[0].workerId,worker=floor.workers.get(w)!;
  assert.equal(worker.provider,'codex');assert.equal(worker.worktree!.base,masterHead);assert.notEqual(worker.worktree!.path,master.worktree!.path);
  assert.equal(saved().find((v:any)=>v.id===w).masterWorkers.role,'worker');
  assert.equal((await call(w,'/office/workers/pr',{pr:1})).status,403);
  assert.equal((await act(w,{action:'takeover',task:'api',complete:true,evidence:'not master'})).status,400);
  const workerDir=path.join(dir,worker.worktree!.path);writeFileSync(path.join(workerDir,'api.ts'),'export const api = true;\n');git(workerDir,'add','api.ts');git(workerDir,'-c','user.name=Test','-c','user.email=test@example.test','commit','-qm','worker API');const commit=git(workerDir,'rev-parse','HEAD');
  assert.equal((await act(w,{action:'result',task:'api',summary:'Implemented API',commits:[commit],checks:'Checked exported API fixture'})).status,200);
  assert.equal((await act(m,{action:'review',task:'api',accept:true,evidence:'Not yet integrated'})).status,400);
  git(masterDir,'merge','--ff-only',commit);assert.ok(existsSync(path.join(masterDir,'api.ts')));
  assert.equal((await act(m,{action:'review',task:'api',accept:true,evidence:'Inspected and merged worker commit; API export verified'})).status,200);
  assert.equal((await act(m,{action:'dispatch',task:'recovery',choice:{provider:'claude',model:'haiku'},reason:'Scoped recovery task'})).status,200);
  const recovery=(await call(m,'/office/team')).body.current.tasks[1].attempts[0].workerId;
  const recoveryDir=path.join(dir,floor.workers.get(recovery)!.worktree!.path);writeFileSync(path.join(recoveryDir,'partial.ts'),'unfinished work');
  assert.equal((await act(recovery,{action:'result',task:'recovery',summary:'Blocked with partial uncommitted work',commits:[],checks:'Failure evidence',failed:true})).status,200);
  assert.equal((await act(m,{action:'takeover',task:'recovery',complete:true,evidence:'Master confirmed partial work is preserved and handles recovery'})).status,200);
  const url='https://github.com/example/fixture/pull/1';
  writeFileSync(pulls,JSON.stringify([{number:1,title:'API',state:'OPEN',isDraft:false,url,headRefName:master.worktree!.branch,headRefOid:commit,baseRefName:'main',labels:[],author:{login:'tester'},body:'Verified API',statusCheckRollup:[]} ]));
  await floor.forge.pulls.refresh();
  assert.equal((await act(m,{action:'finish',pr:url,summary:'Done',checks:'Final validation passed'})).status,400,'checklist is required');
  const completion=(await call(m,'/office/workers/completion')).body;
  assert.equal((await call(m,'/office/workers/complete',{revision:completion.revision,summary:'Verified all requirements',checks:[{name:'API export',status:'passed',evidence:'Read and verified merged api.ts'}],files:['api.ts','contract.ts'],pr:url,commit})).status,200);
  const finished=await act(m,{action:'finish',pr:url,summary:'Completed API and integration',checks:'Verified merged fixture and final commit'});assert.equal(finished.status,200,JSON.stringify(finished.body));assert.equal(finished.body.current.phase,'done');assert.equal(finished.body.current.pr,url);
  assert.equal(git(dir,'status','--porcelain','--untracked-files=no'),'','shared checkout stays untouched');
  assert.equal(office.floors().length,0,'the office never opens the host checkout as a local floor');
  ws.send(JSON.stringify({t:'master-workers.control',action:'stop'}));await wait(()=>!floor.workers.get(m));assert.ok(existsSync(masterDir));assert.ok(existsSync(workerDir));assert.equal(readFileSync(path.join(recoveryDir,'partial.ts'),'utf8'),'unfinished work');assert.ok(floor.workers.get(observer.id),'unrelated observer remains hired');
 }finally{ws?.terminate();hostWs?.terminate();host?.shutdown();hooks.close();office.shutdown();process.env.PATH=oldPath;await new Promise(r=>setTimeout(r,250));rmSync(dir,{recursive:true,force:true});}
});
