// npm run build && node --import tsx scripts/e2e-menu.mjs
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readdirSync, rmSync } from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { execFileSync } from 'node:child_process';
import { chromium } from 'playwright-core';
import { loadConfig } from '../src/server/config.ts';
import { startServer } from '../src/server/server.ts';
const output=path.resolve(process.env.MENU_ARTIFACTS??'/tmp/agent-office-menu-evidence');mkdirSync(output,{recursive:true});
const dir=mkdtempSync(path.join(os.tmpdir(),'office-team-browser-')),binary=path.join(dir,'claude');
writeFileSync(binary,`#!${process.execPath}\nsetInterval(()=>{},1000);\n`,{mode:0o755});
execFileSync('git',['init','-q','-b','main'],{cwd:dir});execFileSync('git',['-c','user.name=Test','-c','user.email=test@example.test','commit','--allow-empty','-qm','fixture'],{cwd:dir});
const cfg=loadConfig([dir,'--password','team-browser','--no-open','--agent',binary]);cfg.port=0;
const office=await startServer(cfg,{publicDir:path.resolve('dist/public')}),base=`http://127.0.0.1:${office.server.address().port}`;
const cache=path.join(os.homedir(),'.cache/ms-playwright'),executable=process.env.CHROMIUM_PATH??path.join(cache,readdirSync(cache).find(x=>x.startsWith('chromium-')),'chrome-linux64/chrome');
const errors=[],checks=[];let browser,page;
const check=(name)=>{checks.push({name,status:'passed'});console.log('PASS '+name);};
try {
 browser=await chromium.launch({executablePath:executable,headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 // Focus/menu checks exercise the shared game without expensive software-GPU scene draws.
 await context.addInitScript(()=>{const raf=window.requestAnimationFrame.bind(window);window.requestAnimationFrame=cb=>raf(ts=>{const r=window.__office?.renderer;if(r)r.render=()=>{};cb(ts);});});
 await context.addInitScript(()=>localStorage.setItem('agent-office.profile',JSON.stringify({name:'Team tester',color:'#ef476f',look:{skin:0,hair:0,style:0}})));
 const login=await context.request.post(base+'/api/login',{data:{password:'team-browser'}});assert.ok(login.ok());
 page=await context.newPage();page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/');
 await page.waitForFunction(()=>window.__office?.player);
 await page.keyboard.press('Tab');
 const menu=page.getByRole('dialog',{name:'Office menu'});
 await menu.waitFor();
 const search=page.getByRole('searchbox',{name:'Search office menu'});
 await search.fill('communications');
 assert.equal(await menu.getByRole('menuitem').count(),1);
 await search.fill('nothing matches xyz');
 await page.getByText('No matches. Try another search.').waitFor();
 await search.fill('');
 await page.getByRole('button',{name:'Pinned',exact:true}).click();
 await page.getByRole('button',{name:'Open',exact:true}).click();
 await page.getByRole('button',{name:'Pin Issues to the top bar',exact:true}).click();
 await page.getByRole('button',{name:'Pinned',exact:true}).click();
 await menu.getByRole('menuitem',{name:/Issues/}).waitFor();
 await page.getByRole('button',{name:'All',exact:true}).click();
 await page.screenshot({path:path.join(output,'menu-desktop.png')});
 await page.getByRole('button',{name:'Display',exact:true}).click();
 const workers=menu.getByRole('menuitemcheckbox',{name:/Workers/});
 const before=await workers.getAttribute('aria-checked');await workers.click();
 assert.notEqual(await workers.getAttribute('aria-checked'),before);
 await search.fill('settings');
 await search.press('ArrowDown');
 assert.equal(await page.evaluate(()=>document.activeElement?.getAttribute('role')),'menuitem');
 await page.setViewportSize({width:390,height:844});
 await search.fill('');await page.getByRole('button',{name:'All',exact:true}).click();
 await page.screenshot({path:path.join(output,'menu-mobile.png')});
 assert.ok(await menu.evaluate(el=>el.getBoundingClientRect().bottom<=innerHeight));
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await menu.getByRole('button',{name:'Close',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('.backdrop')&&window.__office.player.enabled&&window.__office.player.hasMouse);
 await page.keyboard.press('Tab');await page.keyboard.press('Escape');
 await page.waitForFunction(()=>!document.querySelector('.backdrop')&&window.__office.player.enabled&&window.__office.player.hasMouse);
 check('Search, empty results, categories, pinning, display toggles, keyboard navigation, responsive sizing and mouse-look restoration');
 assert.deepEqual(errors,[]);
 writeFileSync(path.join(output,'checks.json'),JSON.stringify(checks,null,2));
} finally {await browser?.close();await office.shutdown();rmSync(dir,{recursive:true,force:true});}
